export type AtomDisplay = 'bs'|'sphere'|'none'
export type BondDisplay = 'stick'|'wireframe'|'none'
export type SolidType = 'metal'|'ionic'|'molecular'|'covalent'
export type HBondDisplay = 'hbond'|'none'
export type PolyhedraDisplay = 'translucent'|'plain'|'collapsed'|'none'